# Generated by Django 5.0.4 on 2024-04-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebOquartier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="VotreModele",
        ),
    ]
